import Head from 'next/head'

const Home = () => (
  <div className='container'>
    <Head>
      <title>Polon - NextJS Boilerplate</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
    </Head>
    <main>
      <h1>NextJS Boilerplate</h1>
      <h2>Arthur Polon</h2>
    </main>
  </div>
)

export default Home
