import axios from 'axios'
import Head from 'next/head'
import { useState } from 'react'

const Home = () => {
  const [input, setInput] = useState('')

  const onClick = async () => {
    const response = await axios.get(`/api/summoner-by-name/${input}`)

    console.log(response)
  }

  return (
    <div className='container'>
      <Head>
        <title>Polon - NextJS Boilerplate</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <h1>NextJS Boilerplate</h1>
        <h2>Arthur Polon</h2>
        <input
          type='text'
          value={input}
          onChange={(e) => setInput(e.target.value)}
        />
        <button onClick={onClick} type='button'>
          Click to search
        </button>
      </main>
    </div>
  )
}

export default Home
