import axios, { AxiosError } from 'axios'
import Head from 'next/head'
import { useState } from 'react'
import clone from '~utils/clone'

const Home = () => {
  const [input, setInput] = useState('')
  const [output, setOutput] = useState('')

  const onClick = async () => {
    try {
      const response = await axios.get(`/api/summoner-by-name/${input}`)

      setOutput(JSON.stringify(response))
    } catch (e) {
      if (e.isAxiosError) {
        const error: AxiosError = clone(e)

        switch (error.response.status) {
          case 404:
            setOutput('Summoner not found')
            break
          default:
            setOutput('An error ocurred')
        }
      }
    }
  }

  return (
    <div className='container'>
      <Head>
        <title>Polon - NextJS Boilerplate</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <h1>NextJS Boilerplate</h1>
        <h2>Arthur Polon</h2>
        <input
          type='text'
          value={input}
          onChange={(e) => setInput(e.target.value)}
        />
        <button onClick={onClick} type='button'>
          Click to search
        </button>
        {output}
      </main>
    </div>
  )
}

export default Home
